In [3]:
import pandas as pd

In [8]:
#importing the Dataset
df=pd.read_csv(r"C:\Users\Dell\Downloads\python_prac\employee_sales.csv")

In [6]:
df.head() # for show top 5 rows

   EmployeeID           Name   Age Department   Salary  YearsOfService
0         1.0     John Smith  34.0         IT  75000.0             5.0
1         NaN            NaN  28.0         HR  60000.0             3.0
2         3.0  Michael Brown   NaN      Sales      NaN             2.0
3         4.0   Sophia Davis  45.0  Marketing  80000.0             NaN
4         NaN            NaN  36.0        NaN  65000.0             4.0

In [9]:
df.head(10) #for show custom top rows

,employee_id,employee_name,department,region,product_category,salary,units_sold,sales_amount,hire_date
0,1,Alice Johnson,Sales,North,Electronics,75000,45,22500,15-03-2022
1,2,Bob Smith,Marketing,South,Clothing,68000,0,0,20-01-2023
2,3,Carol White,Sales,East,Electronics,72000,62,31000,10-11-2021
3,4,David Brown,HR,West,Home,55000,0,0,05-02-2024
4,5,Eva Davis,Sales,North,Clothing,78000,38,11400,12-08-2022
5,6,Frank Miller,Marketing,East,Electronics,65000,0,0,18-06-2023
6,7,Grace Lee,Sales,South,Home,71000,55,16500,25-09-2021
7,8,Henry Wilson,IT,West,Electronics,85000,0,0,30-04-2022
8,9,Ivy Martinez,Sales,East,Clothing,74000,48,14400,14-03-2023
9,10,Jack Anderson,HR,North,Home,52000,0,0,08-01-2024

In [10]:
df.tail() # for show bottom 5 rows

,employee_id,employee_name,department,region,product_category,salary,units_sold,sales_amount,hire_date
95,96,Sam Pike,Marketing,West,Clothing,79500,0,0,07-04-2023
96,97,Tina Quinn,Sales,East,Electronics,88500,77,38500,19-06-2021
97,98,Uma Reed,HR,North,Home,67000,0,0,25-04-2024
98,99,Vince Stone,Sales,West,Clothing,83500,52,15600,03-06-2022
99,100,Willa Tate,IT,South,Electronics,101000,0,0,12-07-2022

In [ ]:
df.tail(10) # for show bottom custom rows

In [13]:
df["employee_id"] # for show particular column

0       1
1       2
2       3
3       4
4       5
     ...
95     96
96     97
97     98
98     99
99    100
Name: employee_id, Length: 100, dtype: int64

In [14]:
df[["employee_id","employee_name"]]# for show 1 and more  column

    employee_id  employee_name
0             1  Alice Johnson
1             2      Bob Smith
2             3    Carol White
3             4    David Brown
4             5      Eva Davis
..          ...            ...
95           96       Sam Pike
96           97     Tina Quinn
97           98       Uma Reed
98           99    Vince Stone
99          100     Willa Tate

[100 rows x 2 columns]

In [15]:
df.columns  #to check columns name

Index(['employee_id', 'employee_name', 'department', 'region',
       'product_category', 'salary', 'units_sold', 'sales_amount',
       'hire_date'],
      dtype='object')

In [16]:
df.info() # to check columns data type and info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       100 non-null    int64
 1   employee_name     100 non-null    object
 2   department        100 non-null    object
 3   region            100 non-null    object
 4   product_category  100 non-null    object
 5   salary            100 non-null    int64
 6   units_sold        100 non-null    int64
 7   sales_amount      100 non-null    int64
 8   hire_date         100 non-null    object
dtypes: int64(4), object(5)
memory usage: 7.2+ KB

In [17]:
df.isnull().sum() # to check null values and sum is use for check how many data is 0

employee_id         0
employee_name       0
department          0
region              0
product_category    0
salary              0
units_sold          0
sales_amount        0
hire_date           0
dtype: int64

In [9]:
# For Change Any Data Type 
df['units_sold']=df['units_sold'].astype(int)

In [10]:
# for find value counts
df['employee_name'].value_counts()

employee_name
Alice Johnson    1
Levi Gray        1
Wes Quinn        1
Vera Pike        1
Umar Owen        1
                ..
Ella Moore       1
Dan Kim          1
Cathy Park       1
Ben Wong         1
Willa Tate       1
Name: count, Length: 100, dtype: int64

In [11]:
# To check the duplicate value
df.duplicated().sum()

np.int64(0)

In [12]:
df['employee_name'].duplicated().sum()

np.int64(0)