# What is Pandas?

Similar to NumPy, Pandas is one of the most widely used python libraries in data science. It provides high-performance, easy to use structures and data analysis tools. Unlike NumPy library which provides objects for multi-dimensional arrays, Pandas provides in-memory 2d table object called Dataframe. It is like a spreadsheet with column names and row labels.

Hence, with 2d tables, pandas is capable of providing many additional functionalities like creating pivot tables, computing columns based on other columns and plotting graphs. Pandas can be imported into Python using:

pandas is well suited for many different kinds of data:
1.Tabular data with heterogeneously-typed columns, as in an SQL table or Excel spreadsheet
2.Ordered and unordered (not necessarily fixed-frequency) time-series data.
3.Arbitrary matrix data (homogeneously typed or heterogeneous) with row and column labels
4.Any other form of observational/statistical data sets. The data actually need not be labeled at all to be placed into a pandas data structure.
Here are just a few of the things that pandas does well:
    
1.Easy handling of missing data (represented as NaN) in floating point as well as non-floating point data
2.Size mutability: columns can be inserted and deleted from DataFrame and higher dimensional objects
3.Automatic and explicit data alignment: objects can be explicitly aligned to a set of labels, or the user can simply ignore the labels and let Series, DataFrame, etc. automatically align the data for you in computations
4.Powerful, flexible group by functionality to perform split-apply-combine operations on data sets, for both aggregating and transforming data
5.Make it easy to convert ragged, differently-indexed data in other Python and NumPy data structures into DataFrame objects
6.Intelligent label-based slicing, fancy indexing, and subsetting of large data sets
7.Intuitive merging and joining data sets
8.Flexible reshaping and pivoting of data sets
9.Hierarchical labeling of axes (possible to have multiple labels per tick)
10.Robust IO tools for loading data from flat files (CSV and delimited), Excel files, databases, and saving/loading data from the ultrafast HDF5 format
11.Time series-specific functionality: date range generation and frequency conversion, moving window statistics, date shifting and lagging.

### For Official Pandas documentation <a href="https://pandas.pydata.org/docs/#" title ="Pandas Documentation">click here</a>

In [2]:
import pandas as pd
#load library - pd is just an alias. I used pd because it's short and literally abbreviates pandas.
#You can use any name as an alias.

In [ ]:
Some commonly used data structures in pandas are:

1.Series objects: 1D array, similar to a column in a spreadsheet
2.DataFrame objects: 2D table, similar to a spreadsheet
3.Panel objects: Dictionary of DataFrames, similar to sheet in MS Excel

Pandas Series object is created using pd.Series function. Each row is provided with an index and by defaults is assigned numerical values starting from 0.
Like NumPy, Pandas also provide the basic mathematical functionalities like addition, subtraction and conditional operations and broadcasting.

Pandas dataframe object represents a spreadsheet with cell values, column names, and row index labels.
Dataframe can be visualized as dictionaries of Series. Dataframe rows and columns are simple and intuitive to access. Pandas also provide SQL-like functionality to filter, sort rows based on conditions. For example,

In [3]:
people_dict = { "weight": pd.Series([68, 83, 112],index=["alice", "bob", "charles"]),   "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"], name="year"),
"children": pd.Series([0, 3], index=["charles", "bob"]),
"hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),}

In [4]:
people = pd.DataFrame(people_dict)
people

         weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN

In [5]:
people[people["birthyear"] < 1990]

       weight  birthyear  children    hobby
alice      68       1985       NaN   Biking
bob        83       1984       3.0  Dancing

New columns and rows can be easily added to the dataframe. In addition to the basic functionalities, pandas dataframe can be sorted by a particular column.

Dataframes can also be easily exported and imported from CSV, Excel, JSON, HTML and SQL database. Some  essential methods that are present in dataframes are:

1.head(): returns the top 5 rows in the dataframe object
2.tail(): returns the bottom 5 rows in the dataframe
3.info(): prints the summary of the dataframe
4.describe(): gives a nice overview of the main aggregated values over each column

# Examples:

In [6]:
#create a data frame - dictionary is used here where keys get converted to column names and values to row values.
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})
data

    Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [7]:
#We can do a quick analysis of any data set using:
data.describe()

             Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

Remember, describe() method computes summary statistics of integer / double variables. To get the complete information about the data set, we can use info() function.

In [8]:
#Among other things, it shows the data set has 5 rows and 2 columns with their respective names.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes

In [9]:
#Let's create another data frame.
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

  group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [10]:
#Let's sort the data frame by ounces - inplace = True will make changes to the data
data.sort_values(by=['ounces'],ascending=True,inplace=False)

  group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [11]:
#We can sort the data by not just one column but multiple columns as well.
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

  group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

Often, we get data sets with duplicate rows, which is nothing but noise. Therefore, before training the model, we need to make sure we get rid of such inconsistencies in the data set. Let's see how we can remove duplicate rows.

In [12]:
#create another data with duplicated rows
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data

    k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [13]:
#sort values 
data.sort_values(by='k2')

    k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [14]:
#remove duplicates - ta da! 
data.drop_duplicates()

    k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

Here, we removed duplicates based on matching row values across all columns. Alternatively, we can also remove duplicates based on a particular column. Let's remove duplicate values from the k1 column.

In [15]:
data.drop_duplicates(subset='k1')

    k1  k2
0  one   3
3  two   3

Now, we will learn to categorize rows based on a predefined criteria. It happens a lot while data processing where you need to categorize a variable. For example, say we have got a column with country names and we want to create a new variable 'continent' based on these country names. In such situations, we will require the steps below:

In [16]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

Now, we want to create a new variable which indicates the type of animal which acts as the source of the food. To do that, first we'll create a dictionary to map the food to the animals. Then, we'll use map function to map the dictionary's values to the keys. Let's see how is it done.

In [17]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'honey ham':
        return 'pig'
    else:
        return 'salmon'


#create a new variable
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [18]:
#another way of doing it is: convert the food values to the lower case and apply the function
lower = lambda x: x.lower()
data['food'] = data['food'].apply(lower)
data['animal2'] = data.apply(meat_2_animal, axis='columns')
data

          food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

Another way to create a new variable is by using the assign function. With this tutorial, as you keep discovering the new functions, you'll realize how powerful pandas is.

In [19]:
data.assign(new_variable = data['ounces']*10)

          food  ounces  animal animal2  new_variable
0        bacon     4.0     pig     pig          40.0
1  pulled pork     3.0     pig     pig          30.0
2        bacon    12.0     pig     pig         120.0
3     pastrami     6.0     cow     cow          60.0
4  corned beef     7.5     cow     cow          75.0
5        bacon     8.0     pig     pig          80.0
6     pastrami     3.0     cow     cow          30.0
7    honey ham     5.0     pig     pig          50.0
8     nova lox     6.0  salmon  salmon          60.0

In [20]:
#Let's remove the column animal2 from our data frame.
data.drop('animal2',axis='columns',inplace=True)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

We frequently find missing values in our data set. A quick method for imputing missing values is by filling the missing value with any random number. Not just missing values, you may find lots of outliers in your data set, which might require replacing. Let's see how can we replace values.

In [21]:
#Series function from pandas are used to create arrays
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [23]:
#replace -999 with NaN values
import numpy as np
data.replace(-999, np.nan,inplace=True)
data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [24]:
#We can also replace multiple values at once.
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace([-999,-1000],np.nan,inplace=True)
data

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

Now, let's learn how to rename column names and axis (row names).

In [25]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [26]:
#Using rename function
data.rename(index = {'Ohio':'SanF'}, columns={'one':'one_p','two':'two_p'},inplace=True)
data

          one_p  two_p  three  four
SanF          0      1      2     3
Colorado      4      5      6     7
New York      8      9     10    11

In [27]:
#You can also use string functions
data.rename(index = str.upper, columns=str.title,inplace=True)
data

          One_P  Two_P  Three  Four
SANF          0      1      2     3
COLORADO      4      5      6     7
NEW YORK      8      9     10    11

Next, we'll learn to categorize (bin) continuous variables.

In [28]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

We'll divide the ages into bins such as 18-25, 26-35,36-60 and 60 and above.

In [29]:
#Understand the output - '(' means the value is included in the bin, '[' means the value is excluded
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [30]:
#To include the right bin value, we can do:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [32]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

Also, we can pass a unique name to each label.

In [35]:
bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
new_cats = pd.cut(ages, bins,labels=bin_names)

pd.value_counts(new_cats)

Youth         5
YoungAdult    3
MiddleAge     3
Senior        1
dtype: int64

In [36]:
#we can also calculate their cumulative sum
pd.value_counts(new_cats).cumsum()

Youth          5
YoungAdult     8
MiddleAge     11
Senior        12
dtype: int64

Let's proceed and learn about grouping data and creating pivots in pandas. It's an immensely important data analysis method which you'd probably have to use on every data set you work with.

In [37]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  1.214622 -0.153652
1    a  two  0.322079 -0.629798
2    b  one  0.514123  0.387184
3    b  two  1.967493  1.532801
4    a  one -1.130580  0.983506

In [39]:
#calculate the mean of data1 column by key1
grouped = df['data1'].groupby(df['key1'])
grouped.mean()

key1
a    0.135374
b    1.240808
Name: data1, dtype: float64

In [40]:
#Now, let's see how to slice the data frame.
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

                   A         B         C         D
2013-01-01 -0.277997  1.477649 -1.003571 -0.700043
2013-01-02 -0.278447  0.661146 -0.246766 -0.178021
2013-01-03  1.452215 -0.157721 -0.273467 -1.109059
2013-01-04  0.099339 -1.858205 -0.101087 -0.562752
2013-01-05  1.941126  1.265417 -0.832624  0.409474
2013-01-06 -0.103103  1.926745  1.032938 -0.262425

In [41]:
#get first n rows from the data frame
df[:3]

                   A         B         C         D
2013-01-01 -0.277997  1.477649 -1.003571 -0.700043
2013-01-02 -0.278447  0.661146 -0.246766 -0.178021
2013-01-03  1.452215 -0.157721 -0.273467 -1.109059

In [42]:
#slice based on date range
df['20130101':'20130104']

                   A         B         C         D
2013-01-01 -0.277997  1.477649 -1.003571 -0.700043
2013-01-02 -0.278447  0.661146 -0.246766 -0.178021
2013-01-03  1.452215 -0.157721 -0.273467 -1.109059
2013-01-04  0.099339 -1.858205 -0.101087 -0.562752

In [43]:
#slicing based on column names
df.loc[:,['A','B']]

                   A         B
2013-01-01 -0.277997  1.477649
2013-01-02 -0.278447  0.661146
2013-01-03  1.452215 -0.157721
2013-01-04  0.099339 -1.858205
2013-01-05  1.941126  1.265417
2013-01-06 -0.103103  1.926745

In [44]:
#slicing based on both row index labels and column names
df.loc['20130102':'20130103',['A','B']]

                   A         B
2013-01-02 -0.278447  0.661146
2013-01-03  1.452215 -0.157721

In [45]:
#slicing based on index of columns
df.iloc[3] #returns 4th row (index is 3rd)

A    0.099339
B   -1.858205
C   -0.101087
D   -0.562752
Name: 2013-01-04 00:00:00, dtype: float64

In [46]:
#returns a specific range of rows
df.iloc[2:4, 0:2]

                   A         B
2013-01-03  1.452215 -0.157721
2013-01-04  0.099339 -1.858205

In [47]:
#returns specific rows and columns using lists containing columns or row indexes
df.iloc[[1,5],[0,2]]

                   A         C
2013-01-02 -0.278447 -0.246766
2013-01-06 -0.103103  1.032938

In [48]:
#Similarly, we can do Boolean indexing based on column values as well. This helps in filtering a data set based on a pre-defined condition.
df[df.A > 1]

                   A         B         C         D
2013-01-03  1.452215 -0.157721 -0.273467 -1.109059
2013-01-05  1.941126  1.265417 -0.832624  0.409474

In [49]:
#we can copy the data set
df2 = df.copy()
df2['E']=['one', 'one','two','three','four','three']
df2

                   A         B         C         D      E
2013-01-01 -0.277997  1.477649 -1.003571 -0.700043    one
2013-01-02 -0.278447  0.661146 -0.246766 -0.178021    one
2013-01-03  1.452215 -0.157721 -0.273467 -1.109059    two
2013-01-04  0.099339 -1.858205 -0.101087 -0.562752  three
2013-01-05  1.941126  1.265417 -0.832624  0.409474   four
2013-01-06 -0.103103  1.926745  1.032938 -0.262425  three

In [50]:
#select rows based on column values
df2[df2['E'].isin(['two','four'])]

                   A         B         C         D     E
2013-01-03  1.452215 -0.157721 -0.273467 -1.109059   two
2013-01-05  1.941126  1.265417 -0.832624  0.409474  four

In [51]:
#select all rows except those with two and four
df2[~df2['E'].isin(['two','four'])]

                   A         B         C         D      E
2013-01-01 -0.277997  1.477649 -1.003571 -0.700043    one
2013-01-02 -0.278447  0.661146 -0.246766 -0.178021    one
2013-01-04  0.099339 -1.858205 -0.101087 -0.562752  three
2013-01-06 -0.103103  1.926745  1.032938 -0.262425  three

We can also use a query method to select columns based on a criterion. Let's see how!

In [52]:
#list all columns where A is greater than C
df.query('A > C')

                   A         B         C         D
2013-01-01 -0.277997  1.477649 -1.003571 -0.700043
2013-01-03  1.452215 -0.157721 -0.273467 -1.109059
2013-01-04  0.099339 -1.858205 -0.101087 -0.562752
2013-01-05  1.941126  1.265417 -0.832624  0.409474

In [53]:
#using OR condition
df.query('A < B | C > A')

                   A         B         C         D
2013-01-01 -0.277997  1.477649 -1.003571 -0.700043
2013-01-02 -0.278447  0.661146 -0.246766 -0.178021
2013-01-06 -0.103103  1.926745  1.032938 -0.262425

Pivot tables are extremely useful in analyzing data using a customized tabular format. I think, among other things, Excel is popular because of the pivot table option. It offers a super-quick way to analyze data.

In [54]:
#create a data frame
data = pd.DataFrame({'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

  group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [55]:
#calculate means of each group
data.pivot_table(values='ounces',index='group',aggfunc=np.mean)

         ounces
group
a      6.333333
b      7.166667
c      4.666667

In [56]:
#calculate count by each group
data.pivot_table(values='ounces',index='group',aggfunc='count')

       ounces
group
a           3
b           3
c           3

# Summary of Previewing data :

In [57]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
   'col1': ['Item0', 'Item0', 'Item1', 'Item1'],
   'col2': ['Gold', 'Bronze', 'Gold', 'Silver'],
   'col3': [1, 2, np.nan, 4]
})

In [ ]:
# Displays the top 5 rows. Accepts an optional int parameter - num. of rows to show
df.head()

# Similar to head, but displays the last rows
df.tail()

# The dimensions of the dataframe as a (rows, cols) tuple
df.shape

# The number of columns. Equal to df.shape[0]
len(df) 

# An array of the column names
df.columns 

# Columns and their types
df.dtypes

# Converts the frame to a two-dimensional table
df.values 

# Displays descriptive stats for all columns
df.describe()

# SORTING

In [59]:
# Sort rows descendingly by the index
df.sort_index(axis=0, ascending=False)

    col1    col2  col3
3  Item1  Silver   4.0
2  Item1    Gold   NaN
1  Item0  Bronze   2.0
0  Item0    Gold   1.0

In [60]:
#We can also sort by one or multiple columns:
df.sort_values(by=['col2', 'col1'], ascending=False)

    col1    col2  col3
3  Item1  Silver   4.0
2  Item1    Gold   NaN
0  Item0    Gold   1.0
1  Item0  Bronze   2.0

# Selecting/Querying

In [ ]:
#ndividual columns can be selected with the [] operator or directly as attributes:
# Selects only the column named 'col1';
df.col1 

# Same as previous
df['col1'] 

# Select two columns
df[['col1', 'col2']]

In [ ]:
#you can also select by absolute coordinates/position in the frame. Indices are zero based:
# Selects second row
df.iloc[1]
# Selects rows 1-to-3
df.iloc[1:3]
# First row, first column
df.iloc[0,0]
# First 4 rows and first 2 columns
df.iloc[0:4, 0:2]

Most often, we need to select by a condition on the cell values. To do so, we provide a boolean array denoting which rows will be selected. The trick is that pandas predefines many boolean operators for its data frames and series. For example the following expression produces a boolean array:

In [61]:
# Produces and array, not a single value!
df.col3 > 0

0     True
1     True
2    False
3     True
Name: col3, dtype: bool

In [ ]:
#This allows us to write queries like these:
# Query by a single column value
df[df.col3 > 0] 

# Query by a single column, if it is in a list of predefined values
df[df['col2'].isin(['Gold', 'Silver'])] 

# A conjunction query using two columns
df[(df['col3'] > 0) & (df['col2'] == 'Silver')] 

# A disjunction query using two columns
df[(df['col3'] > 0) | (df['col2'] == 'Silver')]

# A query checking the textual content of the cells
df[df.col2.str.contains('ilver')]

# Modifying Data Frames

Pandas’ operations tend to produce new data frames instead of modifying the provided ones. Many operations have the optional boolean inplace parameter which we can use to force pandas to apply the changes to subject data frame.

It is also possible to directly assign manipulate the values in cells, columns, and selections as follows:

In [ ]:
# Modifies the cell identified by its row index and column name
df.at[1, 'col2'] = 'Bronze and Gold' 

# Modifies the cell identified by its absolute row and column indices
df.iat[1,1] = 'Bronze again' 

# Replaces the column with the array. It could be a numpy array or a simple list.
#Could also be used to create new columns
df.loc[:,'col3'] = ['Unknown'] * len(df) 

# Equivalent to the previous
df.col3 = ['Unknown'] * len(df) 

# Removes all rows with any missing values.
df.dropna(how='any') 

# Removes all rows with all missing values.
df.dropna(how='all')

It is often useful to create new columns based on existing ones by using a function. The new columns are often called Derived Characteristics:

In [ ]:
def f(x):
    return x + ' New Column';

# Uses the unary function f to create a new column based on an existing one
df.col4 = f(df.col3) 

def g(x, y):
    return x + '_' + y

# Uses the 2-arg function g to create a new column based on 2 existing columns
df.col4 = g(df.col3, df.col2)

# Dates and Time
When loading data from a CSV, we can tell pandas to look for and parse dates. The parse_dates parameters can be used for that. In the most typical case, you would pass a list of column names as parse_dates:

In [ ]:
dates_df = pandas.read_csv('test.csv', sep=';', parse_dates=['col1', 'col2'])

This will work for most typical date formats. If it does not (i.e. we have a non-standard date format) we need to supply our own date parser:

In [ ]:
import pandas as pd
def custom_parser(s):
    # Specify the non-standard format you need
    return pd.datetime.strptime(s, '%d%b%Y')

dates_df = pd.read_csv('test.csv', sep=';', parse_dates=['col1'], date_parser=custom_parser)

In [ ]:
#Alternatively, if we’ve already loaded the data frame we can change a column from string to a date:
dates_df['col2'] = pandas.to_datetime(dates_df['col2'], format='%d.%m.%Y')

Often we need to work with Unix/Posix timestamps. Converting numeric timestamps to pandas timestamps is easy with the unit parameter:

In [ ]:
# Unit specifies if the time is in seconds('s'), millis ('ms'), nanos('ns') etc.
dates_df['col'] = pd.to_datetime(dates_df['col'], unit='ms')

If we need to parse Posix timestamps while reading CSVs, we can once again resort to converter functions. In the converter function we can use the pandas.to_datetime utility which accepts a unit parameter:

In [ ]:
def timestamp_parser(n):
    # Specify the unit you need
    return pandas.to_datetime(float(n), unit='ms')

dates_df = pandas.read_csv('test.csv', sep=';', parse_dates=['col1'], date_parser=timestamp_parser)

In [ ]:
# We can also convert time/timestamp data to Unix epoch numbers:
# Creates a new numeric column with the timestamp epoch in nanos
dates_df.col4 = pandas.to_numeric(dates_df.col3)